trillek-team/tec

- .travis.yml
- README.md
Travis downloads and install CMake 3.1.3
> Travis uses CMake 3.1

- include/physics/physics-debug-drawer.hpp
- include/resources/mesh.hpp
- include/resources/obj.hpp
- src/components/collisionbody.cpp
- src/graphics/vertex-buffer-object.cpp
- src/main.cpp
- src/physics/physics-debug-drawer.cpp
- src/resources/md5mesh.cpp
- src/resources/obj.cpp
- src/test_data.cpp
- src/voxelvolume.cpp
Please tell me if you know of any others
> A few spelling corrections

- .gitattributes
- .gitmodules
- CMakeLists.txt
- include/event-queue.hpp
- include/events.hpp
- include/filesystem.hpp
- include/gui/console.hpp
- include/imgui-system.hpp
- include/os.hpp
- include/render-system.hpp
- include/sound-system.hpp
- include/vcomputer-system.hpp
- src/filesystem.cpp
- src/graphics/shader.cpp
- src/graphics/texture-object.cpp
- src/gui/console.cpp
- src/imgui-system.cpp
- src/main.cpp
- src/os.cpp
- src/physics/physics-debug-drawer.cpp
- src/render-system.cpp
- src/resources/md5anim.cpp
- src/resources/md5mesh.cpp
- src/resources/obj.cpp
- src/resources/pixel-buffer.cpp
- src/resources/vorbis-stream.cpp
- src/sound-system.cpp
- src/test_data.cpp
- src/vcomputer-system.cpp
- tests/filesystem_test.cpp
- Implements a GUI console that hides/shows with ESC key
- Adds a lightweight logger that sinks to stdout and to GUI Console
- Implements a stub dumb command interpreter, that should be replaced/refactor when we have LUA scripting working
- Updated assets
- FilePath::GetAssetsBasePath() now generates always absolute paths
Fix #22 and close #48 
Note : Do the merge of assets BEFORE (dev branch on my fork)
> GUI Console, Logging and other minor issues

- appveyor.yml
> Working Appveyor

- include/gui/abs_window.hpp
- include/gui/console.hpp
- include/gui/entity_tree.hpp
- include/ring_buffer.hpp
- src/gui/console.cpp
- src/gui/entity_tree.cpp
- src/main.cpp
- src/os.cpp
Some minor improvements and re-factoring of GUI code.
- Error / Warning messages have now color
- ring buffer implementation -> Stores console output buffer
- move entity tree to his own class. console and entity tree shares some basic functionality (hide/show, opacity, colapse)
> Improve gui

- .travis.yml
Should have fix these error with clang
> Avoid error on travis

- src/os.cpp
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/trillek-team/tec/68)
> Flush the error cache to discard GLEW related errors

- AUTHORS.txt
- src/filesystem.cpp
- tests/filesystem_test.cpp
I changed a few things in the tests. u8 in front of strings brought a few errors, so I removed it since it worked just as well without. A test didn't work because "€" can't be used in std::strings. I also reworked the directory creation, it didn't work recursively before for some reason.
> Fix the tests, add name to AUTHORS.txt

- common/game-state.hpp
Fairly simple change, made a while ago but forgot to push. I've brought it forward to current revision.
> Added default case to switch in game-state.hpp

- appveyor.yml
> Appveyor caching and artifact deploying

- client/CMakeLists.txt
- client/graphics/animation.cpp
- client/graphics/animation.hpp
- client/main.cpp
- client/render-system.cpp
- client/render-system.hpp
- client/resources/md5mesh.hpp
- client/resources/pixel-buffer.cpp
- client/resources/pixel-buffer.hpp
- client/resources/vorbis-stream.cpp
- client/server-connection.cpp
- client/server-connection.hpp
- client/sound-system.hpp
- client/voxel-volume.cpp
- common/CMakeLists.txt
- common/components/collision-body.cpp
- common/controllers/fps-controller.cpp
- common/controllers/fps-controller.hpp
- common/event-queue.hpp
- common/filesystem.cpp
- common/server-message.hpp
- common/types.hpp
- server/CMakeLists.txt
- server/client-connection.hpp
Add PRI_* macros for eid, game_state_id_t, etc. so that they work the
same across platforms.
> Fix many -Wall warnings

- client/imgui-system.cpp
- client/imgui-system.hpp
- client/main.cpp
- client/server-connection.cpp
- client/server-connection.hpp
also added functionality for the console command "connect" to work the
same as the gui.
the function pointer onConnect is kinda messy and we'll probably want to consider a better way to do for the future.
P.S. In main I needed to change the Opengl subversion to 3.3, cause when it uses 3.1 it causes the window initialization to fail for me.
> Moved imgui code from main to imgui-system

- .gitignore
- CMakeLists.txt
- client/CMakeLists.txt
- client/imgui-system.cpp
- client/imgui-system.hpp
- client/main.cpp
- client/os.cpp
- common/filesystem.cpp
I did not gate the changes to IMGUI system behind an APPLE check.  There should not be an issue with using element buffers to store the indices in compatibility mode, but you might want to test this change on Windows before merging.
> macOS build fixes

- .gitmodules
- CMakeLists.txt
- README.md
- appveyor.yml
- client/CMakeLists.txt
- client/graphics/gbuffer.cpp
- client/graphics/gbuffer.hpp
- client/graphics/view.hpp
- client/gui/console.hpp
- client/imgui-system.cpp
- client/imgui-system.hpp
- client/main.cpp
- client/os.hpp
- client/render-system.cpp
- client/render-system.hpp
- client/resources/obj.cpp
- client/test-data.cpp
- common/components/collision-body.hpp
- common/components/transforms.hpp
- common/controllers/fps-controller.cpp
- common/controllers/fps-controller.hpp
- common/physics-system.cpp
- common/resources/mesh.hpp
- common/server-message.hpp
- server/CMakeLists.txt
- server/client-connection.cpp
- server/main.cpp
Removed imgui submodule in favor of package dep
> It renders again

- .gitignore
- CMakeLists.txt
- client/CMakeLists.txt
- common/CMakeLists.txt
- server/CMakeLists.txt
> Cleaned up the cmake files by preferring the cmake config files

- appveyor.yml
Also installing it to another dir to allow caching.
> Trying to get appveyor linux cache working again

- README.md
> Updated README to reflect using vcpkg in osx and simplify it for other platforms [skip ci]

- .gitmodules
- CMakeLists.txt
- appveyor.yml
- client/CMakeLists.txt
- client/main.cpp
- client/server-connection.cpp
- client/server-connection.hpp
- common/components/transforms.cpp
- server/CMakeLists.txt
- server/server.cpp
- tests/CMakeLists.txt
- tests/client-server-connection.cpp
This might fix #121 and #123 might already be fixed
> Improved connection flow

- .github/workflows/tec.yml
This is just to test out actions, sorry @milesrout I am about to add a commit to master that will probably just need some tweaks.
> Testing out the actions automation

- client/main.cpp
- common/events.hpp
- common/simulation.cpp
- server/client-connection.cpp
- server/client-connection.hpp
- server/main.cpp
- server/server.hpp
Did a format on server/main.cpp of sorts.
Removed a magic number and replaced with constant.
Might address #123 as there was a chance that memory was freed before it was touched last.
> Attempting to fix crash on stop for server

- CMakeLists.txt
- client/imgui-system.cpp
- client/imgui-system.hpp
- client/main.cpp
- client/resources/stb_vorbis.c
- client/resources/vorbis-stream.cpp
- client/resources/vorbis-stream.hpp
Fixed a couple size mismatches and unreferenced params.
A block related to APPLE and asio was also removed as this maybe redundant now.
> Improve warning on MSVC to not display from external libraries

- .github/workflows/tec.yml
This matrix covers win32 and win64, ubuntu 18 and 16, as well as macOS
> Convert GitHub actions to use build matrix  [skip appveyor]

- CMakeLists.txt
- client/CMakeLists.txt
- client/gui/console.hpp
- client/main.cpp
- client/sound-system.hpp
- server/client-connection.cpp
- server/main.cpp
- server/server.cpp
Newest protobuf needed some warning fixes as well.
> Fix build with newer version of spdlog

- appveyor.yml
Trying to fix missing archives error
> Added apt-get update for appveyor

- client/graphics/texture-object.cpp
- client/os.cpp
Enabled automatic mipmap creation.
Added anisotropic filtering to clarify textures with lines at a distance.
> Added multi-sample window creation hint

- README.md
- client/CMakeLists.txt
See issue #179
Added version checking to linking in cmake
Tested as working by changing required version accordingly.
> Fixed build linking error osx v11.0.1

- client/game.hpp
- client/os.cpp
- common/simulation.hpp
Fix some compiler warnings that were introduced in with the focus capture/blur events.
> Fix some compiler warnings

- client/CMakeLists.txt
- client/game.cpp
- client/game.hpp
- client/gui/debug-info.cpp
- client/gui/debug-info.hpp
- client/imgui-system.cpp
- client/main.cpp
My fan spins like a turbine after a few minutes, which prompted me to check what the cause was.
Window displays frames per second.
[Screenshot](https://i.imgur.com/qvfpK0S.png)
> Debug window with FPS

- .github/workflows/tec.yml
> Add back windows-latest to build matrix and adjust ubuntu to use installed gcc-7

- client/game.cpp
- client/game.hpp
- client/gui/debug-info.cpp
- client/os.cpp
- client/os.hpp
- client/time-frame-metrics.hpp
A procentile display of time spend on each section has been added.
An average time per frame has also been added.
[screenshot](https://i.imgur.com/8IYKwOH.png)
> Additional debug info about time spend on each section

- client/main.cpp
- common/events.hpp
- common/lua-system.cpp
- common/lua-system.hpp
- common/proto/commands.proto
- common/server-message.hpp
- server/client-connection.cpp
Updated assets to have example event handler
> Add a basic chat command event and pass the command/args to lua handler

- client/game.cpp
- client/game.hpp
- client/gui/debug-info.hpp
- client/os.cpp
- common/lua-system.cpp
ran clang-format on a few files
> Formatting pass

- README.md
- docs/index.md
- docs/lua/callbacks.md
- docs/lua/classes/client_connection_info.md
- docs/lua/index.md
- mkdocs.yml
Adds a starter setup for mkdocs to begin documenting lua API in repo.
Having a centralized in repo docs is super important for being able to move to a new hosted platform if the need arrives. Additionally this provides a central source of truth for docs. 
The plan is to try a service such as https://readthedocs.org/ to provide a hosted copy as well.
Docs have been server locally via `mkdocs serve` and appear similar to the included screenshot
> Added docs starter

- client/game.cpp
- client/render-system.cpp
- client/render-system.hpp
- common/components/collision-body.hpp
- common/physics-system.cpp
- common/save-game.cpp
- common/user/user.cpp
- common/user/user.hpp
- server/main.cpp
Read state data from Multiton instead of game state in RenderSystem.
Properly handle position and orientation loading/unloading in PhysicsSystem.
Closes #217
> Update position and orientation when motion state is updated

- .github/workflows/tec.yml
See https://github.com/actions/virtual-environments/issues/2950
> Remove ubuntu 16 using gcc 7 as the environment only has gcc 9

- client/game.cpp
- client/game.hpp
- client/manipulators/placement.cpp
- client/manipulators/placement.hpp
Send onKeyUp event to lua from game.cpp.
> Register placement manipulator with lua

- .github/workflows/format.yml
> Change to use PAT for format action

- .github/workflows/format.yml
> Missed quotes around template

- .github/workflows/format.yml
> Too much indentation

- .github/workflows/format.yml
> Specify target branch for committing changes

- .github/workflows/format.yml
> Use PAT during actions

- .github/workflows/format.yml
Disable format workflow temporarily
> Delete accidental doxybook2 addition

- README.md
- client/CMakeLists.txt
- client/graphics/gbuffer.hpp
- client/graphics/lights.hpp
- client/graphics/material.hpp
- client/graphics/shader.hpp
- client/graphics/texture-object.cpp
- client/graphics/texture-object.hpp
- client/graphics/vertex-buffer-object.hpp
- client/imgui-system.hpp
- client/os.cpp
- client/os.hpp
- client/render-system.hpp
- vcpkg.json
> Replace GLEW with GLAD

- .github/workflows/tec.yml
- README.md
- opencppcovconfig.txt
- tests/filesystem_test.cpp
> Add code coverage on windows

- .cmake-format.yaml
- .github/workflows/tec.yml
- CMakeLists.txt
- CMakePresets.json
- client/CMakeLists.txt
- cmake/helpers.cmake
- cmake/link_helpers.cmake
- common/CMakeLists.txt
- server/CMakeLists.txt
- tests/CMakeLists.txt
Add concurrency
Update cmake presets
> Enable running action on push to master

- common/events.hpp
- common/lua-system.cpp
- common/lua-system.hpp
- docs/lua/callbacks.md
- docs/lua/classes/ClientConnection.md
- server/client-connection.cpp
- server/client-connection.hpp
- server/lua-types.cpp
Fixes #184
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/trillek-team/tec/pull/253?shareId=7b017877-d840-4887-a903-e066abeb0e93).
> Expose certain APIs to Lua
