.travis.yml
README.md
travis/build_deps.sh
travis/install_cmake.sh

Should use the new travis ci infrastructure.
Also, saves on cache cmake 3.2, avoiding to recompile all the time.

Modernized travis setup

---

src/filesystem.cpp
src/graphics/animation.cpp
src/graphics/shader.cpp
src/render-system.cpp

Fixed FilePath::DirExists to remove trailing slash on WIN32 due to OS inconsistencies.

Caught some chances to crash if assets didn't load

---

CMakeLists.txt
appveyor.yml

Bullet is now handled as ExternalProject on CMake, so uses always the version included as module.
Also, updated to Bullet 2.83.5

Fix issue #57

---

include/os.hpp
src/main.cpp
src/os.cpp

We are using GLSL 3.30 shaders, so the minimun OpengL must be 3.3 .
Also, actually all the GPU s that support OpenGL 3, can support OpenGL
3.3 (including OSX)
Should close #58

Enforce OpenGL 3.3 and check GLSL version

---

src/os.cpp

Fix  #58 as now does a correct checking of OpenGL version and try to apply glfw hints to enforce a opengl version equal or greater that the opengl version request (ie OpenGL must be 3.3 or 4.x)

Better check of OpenGL Version

---

include/graphics/lights.hpp
include/types.hpp
proto/components.pb.cc
proto/components.pb.h
proto/components.proto
src/test_data.cpp
src/types.cpp

We use proto::Component enum values as TypeID value. This make more easy to
follow the track to all, and make more simple to register new component types.
The price is that .protfile component name must be the same that the struct/class
name.
Also, we now have a runtime map of type ID to const char* . This is **necesarry
to map some stuff to Lua**.

Refactor of types.hpp

---

CMakeLists.txt
README.md
client/main.cpp
src/resources/md5mesh.cpp
src/voxelvolume.cpp

This pull request fixes the build for clang (tested with 3.8), and changes CMakeLists.txt to actually check for the right C++ standard (c++14). Also the readme has been updated to tell the updated compiler requirements. Should fix #74 and #76.

Build fix for clang and gcc 6

---

README.md

When I try to follow the current Readme instructions, I get the following error
```
build]~>make TEC
make: *** No rule to make target 'TEC'.  Stop.
```
But when running `make tec` it starts the build.
The platform I'm using is Arch Linux.

Correct the name of the make target

---

README.md

I've modified the suggested URL in the issue description to use the 'shields_badge' rather than 'badge' format for Semaphore, as the 'badge' format is dissimilar visually from the Appveyor badge.
Closes #120

Update build status badges in README.md

---

common/filesystem.hpp
server/main.cpp

Changed resolution of path for the server to use the simple path variable, but may need to change if this breaks with the platform specific code (re: Windows' use of wstring).

Fixed FilePath reference resolution of path

---

client/CMakeLists.txt
client/file-factories.cpp
client/graphics/animation.cpp
client/graphics/renderable.cpp
client/imgui-system.cpp
client/main.cpp
client/render-system.cpp
client/server-connection.hpp
client/sound-system.hpp
client/test-data.cpp
client/voxel-volume.hpp
common/components/lua-script.cpp
common/physics-system.cpp
common/types.hpp

PR #160 should be merged first to fix build errors.
This removed more of test_data and the concept of the in/out functors in an effort to reduce paths that entity creation/updating can diverge or get out of sync.

Remove inout functors

---

client/game.cpp
client/game.hpp
client/graphics/gbuffer.cpp
client/graphics/gbuffer.hpp
client/main.cpp
client/os.cpp
client/os.hpp
client/render-system.cpp
client/render-system.hpp
common/components/lua-script.cpp
common/components/lua-script.hpp
common/default-config.hpp
common/lua-system.cpp
common/lua-system.hpp

Tweaked order of render system initialization to support loading config before attempting to create GL objects.
This config script can be acceessed to get values such as graphics options.
Closes #13

Created config scripts loading, defaults to scripts/config.lua

---

common/controllers/fps-controller.cpp
common/controllers/fps-controller.hpp
common/events.hpp
common/simulation.cpp
common/simulation.hpp
common/vcomputer-system.cpp
common/vcomputer-system.hpp

This will give the ability to click on a entity and have the entity send out a focus captured and blur (no longer has focus) event, and applies this event dispatch to the vcomputer.
There is now 2 new events FocusCaptured and FocusBlurred that indicate which entity has generated the event and which form of input that have captured or blurred.
The VComputer now listens for entity clicked events and if a click is on a computer with a keyboard it sends a FocusCaptured. Upon hitting the ESCAPE key an appropriate FocusBlurred event is sent out.
The simulation listens for these events and sets a flag on all controllers indicated if they have keyboard/mouse focus or not.
Users need a way to interact with the computers, and there was no mechanism to stop the user from moving during input, nor was …

Add the ability to give a computer keyboard focus and prevent controllers from acting on that input

---

server/client-connection.cpp

Fixed compiler warnings by adding missing switch cases

---

client/CMakeLists.txt
client/main.cpp
common/file-factories.hpp
common/simulation.hpp
server/main.cpp

This relocates the file factory map and registration function to a header in the common project. By having it here an instance of the map will be created in all projects that link to tec. Each project must add file factories respectively to it's map by calling AddFileFactory.
Currently the server is unable to have an instance of LuaSystem because it cannot locate the file factories.
Both client and server compile and run.
Fixed a few compiler warnings about simulation not specifying the override keyword in Simulation.

Move file factory creation into a header so it can be instantiated in both client and server

---

common/proto/components.proto
common/vcomputer-system.cpp
common/vcomputer-system.hpp

Changes the Virtual Keyboard's event method to send keycodes according to the keyboard spec
The virtual computer keyboard is supposed to decode characters and provide info about various control codes, it was not/or was wrong.
Tested by writing a TR3200 program that initialized the virtual keyboard and displayed the keycodes and VK "scancodes"
All of visible ASCII, space, return, and backspace, were tested.

Make the VM keyboard send the correct codes

---

client/main.cpp
client/render-system.cpp

Adds calls to glGetError at the beginning and end of frames to prevent them from leaking into other calls.
Adds the ability to fallback to OpenGL 3.3, if the 4.0 isn't supported (because I hate manually patching this in every time).
Fixes a GL error where the GL requires a fragment shader in a pure stencil/depth pipeline.
See issue (https://github.com/trillek-team/tec/issues/192)
Built and run on MacOS 10.12.6, with Intel HD Graphics 3000 (GL 3.3) - The virtual computer in entity 101 rendered it's screen.
With verbose flag "-v" no GL errors reported.

catch GL frame errors, fix errors from a stencil call on Intel/OSX, fixes #192

---

client/sound-system.cpp
client/sound-system.hpp

This commit simply adds a check when the audio file is attempting to load to verify it was loaded. If it wasn't then the component is not create and is not assigned to the respective entity.
A warning is emitted already that it failed to load the file before this PR.

Add checks to ensure an audio file was loaded, otherwise don't create the component

---

client/main.cpp
common/CMakeLists.txt
common/filesystem.cpp
common/filesystem.hpp
common/proto/save_game.proto
common/resources/script-file.hpp
common/save-game.cpp
common/save-game.hpp
server/main.cpp
server/server.cpp
tests/CMakeLists.txt
tests/client-server-connection.cpp
tests/save-game_test.cpp

Fixed issue were in tests FilePath::PATH_SEPARATOR was not being set correctly.
Fixed tests in general.
Entities are no longer loaded on the client and therefore the world will appear empty. The assets that contains the correct set of entities cannot be transmitted over the wire and therefore when you connect the world will remain empty.
The purpose of the SaveGame is to provide an interface into saving/loading the game's state to a file. Currently loaded is the entities within the world as well as the user's state (position) associated with their user_id and username.
When the world entity list is loaded it emits an EntityCreated event for each loaded entity. However it has no way to get the list of entities during save.
If a user is retrieved from the SaveGame::UserList and updated, …

Begin work on save system

---

common/components/lua-script.cpp
common/lua-system.cpp

Adds error handlers to scripts, this allows Lua tracebacks
Also default loads more of the embedded standard library (such as the oh-so-useful `string` lib)
The `print` now correctly applies `tostring` to it's arguments
When something goes wrong with a Lua script, no diagnostics were shown, this adds some.
```lua
print("test", 1, true, nil)  -- test 1 true nil
print(window_width)  -- nil
require("config")
print(window_width)  -- 1024
```

Add some debugging for Lua script errors

---

client/game.hpp
client/server-connection.cpp
client/server-connection.hpp
common/events.hpp
common/net-message.hpp
server/client-connection.cpp
server/server.cpp
tests/net-message_test.cpp

The asio fix is to set work tracking and use `poll()` instead of `run()`
Removed some std::move that the compiler flagged for RVO
Made the client's Connect asynchronous, it will also show the addresses it resolved.
Made client's asio variables static, since there can only be one.
On OS X, asio was not calling handlers in the client code, result was a brick.
Also got rid of a bunch of warnings, they were bothering me.
Run the tests, server, and client on Mac OS X

Workaround an asio bug on OSX, async connect and clean up warnings

---

.github/workflows/tec.yml

The current build pipeline only builds debug versions, which on windows is causing it to look for the Visual C++ **Debug** runtime which is not available as a redistributable.
We should probably be releasing **Release** builds anyways.

Fix workflow not building release builds

---

client/graphics/animation.hpp
client/graphics/gbuffer.cpp
client/graphics/gbuffer.hpp
client/graphics/gl-symbol.hpp
client/graphics/passes/debug-pass.hpp
client/graphics/passes/dir-light-pass.hpp
client/graphics/passes/final-pass.hpp
client/graphics/passes/geometry-pass.hpp
client/graphics/passes/point-light-pass.hpp
client/graphics/passes/render-pass.hpp
client/graphics/render-item.hpp
client/graphics/render-list.hpp
client/graphics/shader.cpp
client/graphics/texture-object.cpp
client/graphics/vertex-buffer-object.hpp
client/graphics/view.hpp
client/graphics/viewport.hpp
client/render-system.cpp
client/render-system.hpp

Rework render system to have passes
Removed all "pass" related code from render system. Added base RenderPass class interface. DRY'd up RenderSystem::Update by storing all passes in a vector and iterating them rather than explicitly laying out the render loop.
Extracted render item list into its own class, moves in the direction of a scene graph.
Made several GBuffer methods const as they were const.
Removed some class state that didn't need to be stored as it was computed from an event, or it was being created every frame regardless.
Extract GLSymbol into it's own file to reduce the size of the RenderSystem files.
This makes the render system a bit more configurable and declarative. This was also an opportunity for me to practice some more modern c++ libraries and features.
I tried to …

Render system code quality cleanup

---

CONTRIBUTING.md

Fixes #149
Add a `CONTRIBUTING.md` file to the repository.
* **Flow for Contributing**: Describe the steps for contributing, including forking the repository, creating a new branch, making changes, submitting a PR, and rebasing to master and merging.
* **Patterns to Use**: Specify the use of lock guards instead of manual lock/unlock blocks and reference the Coding Patterns page in the wiki.
* **What Makes a Good Issue**: Provide guidelines on writing clear and concise issue descriptions, steps to reproduce, expected behavior, and additional context.
* **Release Schedule**: Include information on the project's release schedule.
* **Additional Resources**: Add a link to the wiki for more detailed information and guidelines.
* **Coding Standards**: Include links to the coding standards in …

Add CONTRIBUTING.md document ** Copilot generated for experimenting **

---

client/graphics/animation.cpp
client/graphics/animation.hpp
client/render-system.cpp

Fixes #216
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/trillek-team/tec/pull/252?shareId=1a404e94-c2da-4704-9399-89231e46f675).

Expand animation class to support playing through animations once, and more

---

client/os.cpp
client/resources/vorbis-stream.cpp
common/controllers/fps-controller.hpp
common/event-list.hpp
common/events.hpp
common/game-state.hpp
common/physics-system.cpp
common/simulation.hpp
server/save-game.cpp
tests/CMakeLists.txt
tests/event-list-test.cpp

Address jerky movement from server to client, prevent window closing on focus loss, and implement an EventList for better event batching with corresponding tests. Clean up unused variable warnings.
At present, when moving, it appears to do a double move or delayed move. This was due to a hack "fix" in the physics system update. The fix was no longer needed
Running locally for movement validation

Fix movement issues and improve event handling
